name: Deploy to Shared Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: private/repository
          token: ${{ secrets.TOKEN }}

      - name: Deploy to Shared Hosting
        run: ./deploy.sh
